export const initialProposals = [
  {
    id: 1,
    title: "Install street lights near New Town bus stop",
    description:
      "Improve safety for commuters and local residents after sunset near the main bus stop.",
    ward: "Ward 39",
    area: "New Town",
    category: "Street Lighting",
    status: "open",
    votes: 284,
    notNecessaryVotes: 11,
    voteChoice: null,
    author: "ANUU Sharma",
    createdAt: "2 days ago",
    latitude: 22.5787,
    longitude: 88.4756,
    comments: [
      {
        id: 101,
        author: "Virat_Kohli_18",
        text: "This route is very dark after 8 PM.",
      },
    ],
  },
  {
    id: 2,
    title: "Repair drainage before monsoon in Ward 42",
    description:
      "Clean and repair blocked drains near the market to reduce waterlogging during heavy rain.",
    ward: "Ward 42",
    area: "Salt Lake",
    category: "Water Supply",
    status: "under_review",
    votes: 198,
    notNecessaryVotes: 7,
    voteChoice: null,
    author: "Sharma ji ka beta",
    createdAt: "4 days ago",
    latitude: 22.5781,
    longitude: 88.4313,
    comments: [],
  },
  {
    id: 3,
    title: "Create a shaded public seating area at Rabindra Sarobar",
    description:
      "Add benches, drinking water points, and shade for senior citizens and walkers.",
    ward: "Ward 87",
    area: "South Kolkata",
    category: "Others",
    status: "accepted",
    votes: 156,
    notNecessaryVotes: 18,
    voteChoice: null,
    author: "Crishinooo Ronaldoo",
    createdAt: "1 week ago",
    latitude: 22.5141,
    longitude: 88.3632,
    comments: [
      {
        id: 102,
        author: "Mausii",
        text: "Please include accessible seating too.",
      },
    ],
  },
  {
    id: 4,
    title: "Add safer pedestrian crossings near Park Street Metro",
    description:
      "Install better markings and timed pedestrian signals around busy metro exits.",
    ward: "Ward 63",
    area: "Park Street",
    category: "Roads & Traffic",
    status: "open",
    votes: 121,
    notNecessaryVotes: 9,
    voteChoice: null,
    author: "MAHII",
    createdAt: "1 week ago",
    latitude: 22.5524,
    longitude: 88.3541,
    comments: [],
  },
];

export const initialNotifications = [
  {
    id: 1,
    type: "proposal_status",
    title: "Proposal under review",
    message: "The drainage proposal for Ward 42 is now being reviewed.",
    time: "12 min ago",
    isRead: false,
  },
  {
    id: 2,
    type: "comment",
    title: "New community comment",
    message: "A resident commented on the New Town street lights proposal.",
    time: "1 hour ago",
    isRead: false,
  },
  {
    id: 3,
    type: "system",
    title: "Community voting update",
    message: "This week’s priority list is now available.",
    time: "Yesterday",
    isRead: true,
  },
];
